In [3]:
import matplotlib.pyplot as plt
import numpy as np
a = np.array([[0, 0, 0, 0, 0], 
              [0, 1, 1, 0, 0.5], 
              [1, 0, 1, 0, 0.5]])

b = np.array([[0, 0, 0, 0, 0], 
              [0, 2, 2, 0, 0.5], 
              [2, 0, 2, 0, 0.5]])

c = np.array([[1, 0, 1, 0, 0.5], 
              [0, 0, 0, 0, 0], 
              [0, 1, 1, 0, 0.5]])

In [77]:
def proc(arr):
    res_vec = list()
    for i in arr:
        if not res_vec:
            res_vec.append(i)
        else:
            tmp = i.copy()
            for j in res_vec:
                tmp -=  j * np.dot(i, j)/np.dot(j, j)
            if (tmp != 0).any():
                res_vec.append(tmp)
    return np.array(res_vec)

In [27]:
transform_matrix = [
    np.array([[1, 0, 0],
             [0, 1, 0], 
             [0, 0, 1]]),  
]
bias = np.array([[1, 0, 0],
             [1, 0, 0], 
             [1, 0, 0],
             [1, 0, 0],
             [1, 0, 0]])

In [70]:
for i in transform_matrix:
        instance = np.dot(a.T, i)
        print(np.dot(instance, proc(instance).T))
        
#         print()
#         print(np.linalg.svd(instance))
#         print()
#         instance += bais
#         print("With bias :",  proc(instance))
#         print()
#         print(np.linalg.svd(instance))
#         print()

[[1.  0. ]
 [0.  1. ]
 [1.  1. ]
 [0.  0. ]
 [0.5 0.5]]


In [33]:
t = np.array([[0, 0, 0, 0, 0],
             [1, 0, 0, 1, 0.5], 
             [0, 1, 0, 1, 0.5]])
np.dot(t.T, proc(t.T).T)
proc(t.T)

array([[0., 1., 0.],
       [0., 0., 1.]])

In [69]:
s = np.dot(s, transform_matrix[0])
np.dot(s, proc(s).T)
# s
f  = proc(s).T
g  = proc(a.T).T
# proc(s.T)
print(np.dot(a.T, g))
print(np.dot(s, f))
np.dot(s, transform_matrix[0])

[[1.  0. ]
 [0.  1. ]
 [1.  1. ]
 [0.  0. ]
 [0.5 0.5]]
[[1.  0. ]
 [0.  1. ]
 [1.  1. ]
 [0.  0. ]
 [0.5 0.5]]


array([[ 0. ,  0. , -1. ],
       [ 0. , -1. ,  0. ],
       [ 0. , -1. , -1. ],
       [ 0. ,  0. ,  0. ],
       [ 0. , -0.5, -0.5]])

In [78]:
test = np.array([[0, 0, 0, 0, 0],
                [1, 0, 0, 1, 0.5],
                [0, 1, 0, 1, 0.5]])

In [82]:
np.dot(a, )

array([[1. , 0. ],
       [0. , 1. ],
       [0. , 0. ],
       [1. , 1. ],
       [0.5, 0.5]])